name: Deploy

on:
  deployment_status

jobs:
  run:
  # get all the workflow runs and check which status is pending and paste that workflow run link in the slack message
    runs-on: ubuntu-latest
    steps:
      - name: Get url
        if: ${{ github.event.deployment_status.state == 'pending' }}
        id: get_url
        run: |
          sleep 40
          echo "::set-output name=URL::$(echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
      - name: "Report build errors to #social"
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_GLOBAL_WEBHOOK }}
            SLACK_CHANNEL: social
            SLACK_USERNAME: Definitions Bot
            SLACK_ICON_EMOJI: ":x:"
            SLACK_COLOR: "#FF0000"
            SLACK_TITLE: "Deployment Review requested"
            SLACK_FOOTER: "" 
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  