name: Reusable Pulumi run

on:
 pull_request: {}
 deployment:
  environment:
    name: mariheart"

jobs:
  run:
    environment: mariheart
    runs-on: ubuntu-latest
    steps:
        - name: Say hello
          run: echo "Hello, world!"

  slack-notify:
    if: ${{enviroment == 'mariheart'}}
    runs-on: ubuntu-latest
    steps:
        - name: "Report build errors to #social"
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_GLOBAL_WEBHOOK }}
            SLACK_CHANNEL: social
            SLACK_USERNAME: Definitions Bot
            SLACK_ICON_EMOJI: ":x:"
            SLACK_COLOR: "#FF0000"
            SLACK_TITLE: "Deployment Review requested"
            SLACK_FOOTER: "" 
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}